name: Twooooooo

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - integration

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: echo "Hello ${{github.event.inputs.environment}}"

  test:
    if: ${{ github.event.inputs.environment == 'test' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting test
        run: echo "Hello Test!"

  integration:
    if: ${{ github.event.inputs.environment == 'integration' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting int
        run: echo "Hello Integration!"